steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ferrous-module-446709-u1/github.com/MaheshRavilla2018/testMahesh:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ferrous-module-446709-u1/github.com/MaheshRavilla2018/testMahesh:$COMMIT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY